#pragma once

template <class T>
class CProxy_IBpmCounterCtlEvents : public IConnectionPointImpl<T, &__uuidof(_IBpmCounterCtlEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
